name: Go

on:
  push:
    branches: [ master ]

jobs:

  build:
    name: Build the project
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Start NTS test
      uses: actions/ntx-action@v2
      with:
        domain: 'http://srvwp15.westeurope.cloudapp.azure.com:8084'
        uri: '/NTX/ntxWebService?LinkID=178&TypeID=1&MachineID=132&RepositoryID=2&ProjectID=0bd5b276-08aa-4cd7-b6c1-0f18b7bcf951&Version=92&Cycle=93&UserId=46&ServerURL=18&EnvironmentId=8&Collection=DefaultCollection&Token=qafbanqku4ckwt4jnt7lcretgvfqpo4nthacvoixsvbhnryql2ua'
        username: 'alho'
        password: ${{ secrets.NTX_PASSWORD }}
        wait-time: 10
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Compile
      run: go build -v ./...

  #  - name: Testing
  #    run: go test -v ./...
