name: Go

on:
  push:
    branches: [ master ]

jobs:

  build:

    name: Run test
    runs-on: ubuntu-latest

    steps:
    


http://srvwp15.westeurope.cloudapp.azure.com:8084/NTX
      - name: Run Tests with NTX
        id: NTX
        uses: NTXnoesis/ntx-action@V1.0
        with:
          domain: 'http://srvwp15.westeurope.cloudapp.azure.com:8084/NTX'
          uri: '/ntxWebService?LinkID=2&TypeID=1&MachineID=2&RepositoryID=3&ProjectID=10600&Version=10800&Cycle=PROJ2021-1671&UserId=50&ServerURL=3&EnvironmentId=8'
          username: 'admin'
          password: ${{ secrets.NTX_PASSWORD }}
          wait-time: 10
    
      - name: Get the output
        run: echo "The test was ${{ steps.ntx.outputs.status}}"

   #  - name: Compile
   #     run: go build -v ./...

