name: Go

on:
  push:
    branches: [ master ]

jobs:

  build:
    name: Run test on NTX
    runs-on: ubuntu-latest

    steps:
    #- uses: actions/checkout@v2
    - name: NTX action step
      id: NTX
      uses: noesis-teste/ntx-action@latest
      with:
        ntx-url: 'localhost:8080'

    - name: Get the output
      run: echo "The test was ${{ steps.ntx.outputs.status}}"


    #- name: CURL ask
    #  run: |
    #    apiResults=$(curl https://reqbin.com/echo/get/json -H "Accept: application/json" )
    #    echo "test - $apiResults"
    
   # - name: Set up Go
   #   uses: actions/setup-go@v2
   #   with:
   #     go-version: 1.15

  #  - name: Compile
  #    run: go build -v ./...

  #  - name: Testing
  #    run: go test -v ./...
