name: Go

on:
  push:
    branches: [ master ]

jobs:

  build:
    name: Build the project
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: CURL ask
      run: curl https://www.google.com
    
   # - name: Set up Go
   #   uses: actions/setup-go@v2
   #   with:
   #     go-version: 1.15

  #  - name: Compile
  #    run: go build -v ./...

  #  - name: Testing
  #    run: go test -v ./...
