name: Go

on:
  push:
    branches: [ master ]

jobs:

  build:

    name: Run test
    runs-on: ubuntu-latest

    steps:
      #- uses: actions/checkout@v2  http://srvwd41.westeurope.cloudapp.azure.com:8084/NTX
      # /ntxWebService?LinkID=157&TypeID=1&MachineID=128&RepositoryID=2&ProjectID=0bd5b276-08aa-4cd7-b6c1-0f18b7bcf951&Version=1&Cycle=2&UserId=15&ServerURL=19&EnvironmentId=8&Collection=DefaultCollection&Token=qafbanqku4ckwt4jnt7lcretgvfqpo4nthacvoixsvbhnryql2ua

      # http://localhost:8084/NTX
      # /ntxWebService?LinkID=88&TypeID=1&MachineID=71&RepositoryID=3&ProjectID=10100&Version=10100&Cycle=PDT-2396&UserId=14&ServerURL=3&EnvironmentId=5

      - name: Run Tests with NTX
        id: NTX
        uses: NTXnoesis/ntx-action@V1.0
        with:
          domain: 'http://localhost:8084/NTX'
          uri: '/ntxWebService?LinkID=88&TypeID=1&MachineID=71&RepositoryID=3&ProjectID=10100&Version=10100&Cycle=PDT-2396&UserId=14&ServerURL=3&EnvironmentId=5'
          username: ${{ secrets.NTX_USERNAME }}
          password: ${{ secrets.NTX_PASSWORD }}
          wait-time: 10
    
      - name: Get the output
        run: echo "The test was ${{ steps.ntx.outputs.status}}"

   #  - name: Compile
   #     run: go build -v ./...

